projectName: RollCallSystem
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
  servlet:
    context-path: /${projectName}
  context-path: /${projectName}

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rollcall
    username: RollCall
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  devtools:
    restart:
      exclude: static/**,public/**
  mvc:
    view:
      suffix: .html
#redis配置
  redis:
    database: 0
    host: localhost
    port: 6379
    # 连接超时时间 单位 ms（毫秒）
    timeout: 3000ms
    pool:
    # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
    max-active: 8
    # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
    max-wait: -1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chm.domain

#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#跨域
axios:
  defaults:
    withCredentials: true

#Logback config
logging:
  config: classpath:logback-spring.xml


#日志配置
logging:
  file: MyLog.log



#签到时间配置
NORMALSTART: 20 #正常签到开始时间(上课前20分钟)

NORMALEND: 5 #正常签到结束时间(上课后5分钟)

LATE: 20 #迟到(上课后5分钟至上课后20分钟)

#学期开始时间配置
STARTWEEK: 10 #今年的第几周

#默生人阈值
THRESHOLD: 75.0

#当前学期
SEMESTER: 2016-2017-1